security:
  oauth2:
    client:
      clientId: <clientId>
      clientSecret: <secret>
      accessTokenUri: <accesstokenuri>
      userAuthorizationUri: <userAuthorizationUri>
      clientAuthenticationScheme: form
      scope: openid
    resource:
      userInfoUri: https://graph.windows.net/me?api-version=1.6
spring:
  resources:
    chain:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG