security:
  oauth2:
    client:
      clientId: [clientid]
      clientSecret: [clientsecret]
      accessTokenUri: https://login.microsoftonline.com/[tenant-id]/oauth2/token
      userAuthorizationUri: https://login.microsoftonline.com/[tenant-id]/oauth2/authorize
      clientAuthenticationScheme: form
      scope: openid
    resource:
      userInfoUri: https://graph.windows.net/me?api-version=1.6
spring:
  resources:
    chain:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG